[package]
name = "sql_mini_execution"
version = "0.1.0"
edition = "2021"

[dependencies]
sql_mini_parser = { path = "../sql_mini_parser" }
serde = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
