[package]
name = "sql_mini_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = { version = "0.4.8", features = ["serde"] }
derive_more = { workspace = true }
nom = "8.0.0"
nom_locate = "5.0.0"
serde = { workspace = true }
